# Generated by Django 4.2.10 on 2024-02-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baby',
            fields=[
                ('id_baby', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=56)),
                ('lastname', models.CharField(max_length=56, null=True)),
                ('birthday', models.DateField()),
                ('size', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id_forums', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=56)),
                ('lastname', models.CharField(max_length=56, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('couple', models.BooleanField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('picture_profil', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pregnancie',
            fields=[
                ('id_pregnancy', models.AutoField(primary_key=True, serialize=False)),
                ('pregnancy_date', models.DateField(null=True)),
                ('amenorhea_date', models.DateField(null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_baby.user')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('text_message', models.CharField(max_length=56)),
                ('id_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_baby.forum')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_baby.user')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_baby.user'),
        ),
        migrations.CreateModel(
            name='biberon',
            fields=[
                ('id_biberon', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(null=True)),
                ('nb_biberon', models.IntegerField(null=True)),
                ('id_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_baby.baby')),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_baby.user'),
        ),
    ]
