# Generated by Django 4.2.10 on 2024-02-23 13:02

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='baby',
            fields=[
                ('id_baby', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=56)),
                ('lastname', models.CharField(blank=True, max_length=56, null=True)),
                ('birthday', models.DateField()),
                ('size', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id_forums', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=56)),
                ('lastname', models.CharField(blank=True, max_length=56, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('couple', models.BooleanField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('picture_profil', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pregnancie',
            fields=[
                ('id_pregnancy', models.AutoField(primary_key=True, serialize=False)),
                ('pregnancy_date', models.DateField(blank=True, null=True)),
                ('amenorhea_date', models.DateField(blank=True, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('text_message', models.CharField(max_length=56)),
                ('id_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.forum')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.user')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.user'),
        ),
        migrations.CreateModel(
            name='biberon',
            fields=[
                ('id_biberon', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('nb_biberon', models.IntegerField(blank=True, null=True)),
                ('id_baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.baby')),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.user'),
        ),
    ]
