# Generated by Django 4.2.10 on 2024-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
