# Generated by Django 4.2.10 on 2024-03-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_forum_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biberon',
            name='nb_biberon',
        ),
        migrations.AddField(
            model_name='biberon',
            name='date_biberon',
            field=models.DateField(blank=True, null=True),
        ),
    ]
