# Generated by Django 4.2.10 on 2024-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_biberon_nb_biberon_biberon_date_biberon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biberon',
            name='date_biberon',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
