#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Gradient kivy_gradient.Gradient

<Baby>:
	answer_input1: answer_input1
	answer_input2: answer_input2
	answer_input3: answer_input3
	answer_input4: answer_input4
	answer_input5: answer_input5

	BoxLayout:
		orientation: 'vertical'
		spacing: '5dp'
		padding: '5dp'

		canvas:
			Rectangle:
				pos: self.pos
				size: self.size
				texture: Gradient.vertical(get_color_from_hex("CC99FF"), get_color_from_hex("99CCFF"))

		Button:
			size_hint: None, None
			size: dp(24), dp(24)
			pos_hint: {'top': 1.0, 'left': 1.0}
			background_normal: "fleche_retour.png"
			on_press: root.goBack()

		BoxLayout:
			orientation: 'vertical'
			spacing: '5dp'

			Label:
				text: 'Hello Baby !'
				color: 0, 0, 0, 1
				font_size: 30
				size_hint: 1.0, 0.2
				padding: ('10dp', '10dp')
				background_color: "#99CCFF"

			Image:
				source: "hello_baby_logo.png"
				allow_stretch: False
				keep_ratio: True
				size_hint_y: 0.5

			Label:
				text: 'Création du Profil bébé'
				color: 0, 0, 0, 1
				font_size: 12
				size_hint: 1.0, 0.2
				padding: ('10dp', '10dp')

		GridLayout:
			cols: 2
			spacing: '5dp'
			padding: '30dp'

			Label:
				text: 'Prénom :*'
				color: 0, 0, 0, 1
			TextInput:
				id: answer_input1
				padding: 20, 20, 20, 20
				font_size: 12
				input_type: "text"

			Label:
				text: 'Nom :'
				color: 0, 0, 0, 1
			TextInput:
				id: answer_input2
				padding: 20, 20, 20, 20
				font_size: 12
				input_type: "text"

			Label:
				text: 'Date de naissance :'
				color: 0, 0, 0, 1
			TextInput:
				id: answer_input3
				padding: 20, 20, 20, 20
				font_size: 12
				input_type: "text"

			Label:
				text: 'Poids actuel :'
				color: 0, 0, 0, 1
			TextInput:
				id: answer_input4
				padding: 20, 20, 20, 20
				font_size: 12
				input_type: "text"

			Label:
				text: 'Taille :'
				color: 0, 0, 0, 1
			TextInput:
				id: answer_input5
				padding: 20, 20, 20, 20
				font_size: 12
				input_type: "text"

		Label:
			text: '*obligatoire'
			color: 0, 0, 0, 1
			font_size: 10
			size_hint: 0.2, 0.2
			padding: ('10dp', '10dp')

		Button:
			text: 'Valider le profil'
			color: 1, 1, 1, 1
			size_hint: None, None
			size: 200, 50
			pos_hint: {'center_x': 0.5, 'center_y': 0.5}
			background_color: 'blue'
			on_press: root.create()

		Button:
			text: 'Ajouter un nouveau profil'
			color: 1, 1, 1, 1
			size_hint: None, None
			size: 200, 50
			pos_hint: {'center_x': 0.5, 'center_y': 0.5}
			background_color: 'blue'
			on_press: root.create_new_baby()
