#:kivy 2.0.0
#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Gradient kivy_gradient.Gradient

<Home_baby>:

	BoxLayout:
		orientation: 'vertical'
		spacing: '5dp'
		canvas:
			Rectangle:
				pos: self.pos
				size: self.size
				texture: Gradient.vertical(get_color_from_hex("CC99FF"), get_color_from_hex("99CCFF"))

		Button:
			size_hint: None, None
			size: dp(24), dp(24)
			pos_hint: {'top': 1.0, 'left': 1.0}
			background_normal: "fleche_retour.png"
			on_press: root.goBack()

		BoxLayout:
			orientation: 'horizontal'
			spacing: '5dp'
			size: dp(40), dp(40)
			pos_hint: {'top': 1.0}
			size_hint_y: None
			height: dp(25)

			Image:
				source: "hello_baby_logo_band.png"
				allow_stretch: False
				keep_ratio: False
				size: dp(32), dp(32)

			Label:
				text: 'Hello Baby !'
				color: 0, 0, 0, 1
				font_size: 30
				padding: ('5dp', '5dp')
				background_color: 0.6, 0.8, 1, 1

			Image:
				source: "photo_profil.png"
				allow_stretch: False
				keep_ratio: False
				size: dp(32), dp(32)

		Carousel:
			padding: 50
			marging: 20
			direction: 'right'
			AsyncImage:
				source: 'http://placehold.it/480x270.png&text=slide-1.png'
			AsyncImage:
				source: 'http://placehold.it/480x270.png&text=slide-2.png'
			AsyncImage:
				source: 'http://placehold.it/480x270.png&text=slide-3.png'
			AsyncImage:
				source: 'http://placehold.it/480x270.png&text=slide-4.png'

		FloatLayout:
			size_hint_x: None
			width: dp(430)
			pos_hint: {'center_x': 0.5, 'top': 0.5}

			Image:
				source: "Blocnote.png"
				size_hint: None, None
				size: dp(430), dp(300)
				allow_stretch: True
				keep_ratio: True
				pos_hint: {'center_x': 0.5, 'top': 1.3}

			Label:
				text: "Informations :"
				size_hint: None, None
				size: self.texture_size
				pos_hint: {'center_x': 0.5, 'top': 0.8}
				color: 0, 0, 0, 1
				font_size: 18

		BoxLayout:
			orientation: 'vertical'
			spacing: 10
			padding: 50

			Button:
				text: 'Diagrammes'
				color: 0, 0, 0, 1
				size_hint: 1.0, 0.2
				size_hint_y: None
				height: 80
				size: '50dp', '50dp'
				margin: 20
				background_color: 0, 0, 0, 0
				canvas.before:
					RoundedRectangle:
						pos: self.pos
						size: self.size
						texture: Gradient.vertical(get_color_from_hex("80FF80"), get_color_from_hex("C6FFC6"))
						radius: [15, 15, 15, 15]
				on_press: root.diagrams()

			Button:
				text: 'Rendez-vous'
				color: 0, 0, 0, 1
				size_hint: 1.0, 0.2
				size_hint_y: None
				height: 80
				size: '50dp', '50dp'
				margin: 20
				background_color: 0, 0, 0, 0
				canvas.before:
					RoundedRectangle:
						pos: self.pos
						size: self.size
						texture: Gradient.vertical(get_color_from_hex("FF8080"), get_color_from_hex("FFBFBF"))
						radius: [15, 15, 15, 15]
				on_press: root.appointement()

			Button:
				text: 'Professionnels'
				color: 0, 0, 0, 1
				size_hint: 1.0, 0.2
				size_hint_y: None
				height: 80
				size: '50dp', '50dp'
				margin: 20
				background_color: 0, 0, 0, 0
				canvas.before:
					RoundedRectangle:
						pos: self.pos
						size: self.size
						texture: Gradient.vertical(get_color_from_hex("FF8F59"), get_color_from_hex("FFB997"))
						radius: [15, 15, 15, 15]
				on_press: root.professionnals()

			Button:
				text: 'Forums'
				color: 0, 0, 0, 1
				size_hint: 1.0, 0.2
				size_hint_y: None
				height: 80
				size: '50dp', '50dp'
				margin: 20
				background_color: 0, 0, 0, 0
				canvas.before:
					RoundedRectangle:
						pos: self.pos
						size: self.size
						texture: Gradient.vertical(get_color_from_hex("B76FFF"), get_color_from_hex("DCB9FF"))
						radius: [15, 15, 15, 15]
				on_press: root.forums()

			Button:
				text:'ChatBot'
				color: 0 , 0 , 0 , 1
				size_hint_y: None
				height: 50
				margin: 20
				background_color: 0, 0, 0, 0
				canvas.before:
					RoundedRectangle:
						pos: self.pos
						size: self.size
						texture: Gradient.vertical(get_color_from_hex("F2F200"), get_color_from_hex("FFFF80"))
						radius: [15, 15, 15, 15]
				on_press: root.exchange()

		BoxLayout:
			orientation: 'vertical'
			size_hint_y: None
			height: dp(50)
			canvas:
				Color:
					rgba: 0.25, 0.5, 0.5, 1
				Rectangle:
					pos: self.pos
					size: self.size

			Label:
				text: 'Contact'
				color: 1, 1, 1, 1
				font_size: 20
				height: dp(25)
