<Exchange>:

	BoxLayout:
		orientation: 'vertical'
		spacing: '5dp'
		canvas:
			Color:
				rgba: 0.6, 0.8, 1, 1
			Rectangle:
				pos: self.pos
				size: self.size

		Button:
			size_hint: None, None
			size: dp(24), dp(24)
			pos_hint: {'top': 1.0, 'left': 1.0}
			background_normal: "fleche_retour.png"
			on_press: root.goBack()

		BoxLayout:
			orientation: 'horizontal'
			spacing: '5dp'
			size: dp(40), dp(40)
			pos_hint: {'top': 1.0}
			size_hint_y: None
			height: dp(25)

			Image:
				source: "hello_baby_logo_band.png"
				allow_stretch: False
				keep_ratio: False
				size: dp(32), dp(32)

			Label:
				text: 'Hello Baby !'
				color: 0, 0, 0, 1
				font_size: 30
				padding: ('5dp', '5dp')
				background_color: 0.6, 0.8, 1, 1

			Image:
				source: "photo_profil.png"
				allow_stretch: False
				keep_ratio: False
				size: dp(32), dp(32)

		BoxLayout:
			orientation: 'vertical'
			spacing: 10
			padding: ('50dp', '750dp')
			pos_hint: {'top': 1.0}

			Label:
				text:'Echanges'
				color: 0 , 0 , 0 , 1
				size_hint_y: None
				height: 50
				margin: 20
				canvas.before:
					Color:
						rgba: 242 / 255, 242 / 255, 0 / 255, 1
					RoundedRectangle:
						pos: self.pos
						size: self.size
						radius: [15, 15, 15, 15]

		BoxLayout:
			orientation: 'vertical'
			size_hint_y: None
			height: dp(50)
			canvas:
				Color:
					rgba: 0.25, 0.5, 0.5, 1
				Rectangle:
					pos: self.pos
					size: self.size

			Label:
				text: 'Contact'
				color: 1, 1, 1, 1
				font_size: 20
				height: dp(25)
